wandb_version: 1

activation:
  value: relu
batchsize:
  value: 16
eta:
  value: 0.002
initialization:
  value: he
loss:
  value: cross
max_epochs:
  value: 10
no_of_classes:
  value: 10
no_of_features:
  value: 784
no_of_layers:
  value: 5
no_of_neurons:
  value: 256
optimizer:
  value: adam
weight_decay:
  value: 0
