wandb_version: 1

activation:
  value: relu
batchsize:
  value: 32
eta:
  value: 0.1
initialization:
  value: xavier
loss:
  value: cross
max_epochs:
  value: 10
no_of_classes:
  value: 10
no_of_features:
  value: 784
no_of_layers:
  value: 4
no_of_neurons:
  value: 128
optimizer:
  value: adam
weight_decay:
  value: 0.0005
