wandb_version: 1

activation:
  value: relu
batchsize:
  value: 128
eta:
  value: 0.005
initialization:
  value: he
loss:
  value: cross
max_epochs:
  value: 10
no_of_classes:
  value: 10
no_of_features:
  value: 784
no_of_layers:
  value: 6
no_of_neurons:
  value: 128
optimizer:
  value: nadam
weight_decay:
  value: 0.0005
