wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.6
    start_time: 1678382990.546419
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.10.6
      5: 0.13.11
      8:
      - 1
      - 5
activation:
  desc: null
  value: relu
batchsize:
  desc: null
  value: 32
eta:
  desc: null
  value: 0.005
initialization:
  desc: null
  value: xavier
loss:
  desc: null
  value: cross
max_epochs:
  desc: null
  value: 5
no_of_classes:
  desc: null
  value: 10
no_of_features:
  desc: null
  value: 784
no_of_layers:
  desc: null
  value: 6
no_of_neurons:
  desc: null
  value: 64
optimizer:
  desc: null
  value: nadam
weight_decay:
  desc: null
  value: 0.0005
