wandb_version: 1

_name:
  desc: null
  value: wandb.config
_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.6
    start_time: 1678378182.781173
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.10.6
      5: 0.13.11
      8:
      - 1
      - 4
      - 5
activation:
  desc: null
  value: relu
batchsize:
  desc: null
  value: 256
eta:
  desc: null
  value: 0.0001
initialization:
  desc: null
  value: he
loss:
  desc: null
  value: cross
max_epochs:
  desc: null
  value: 5
no_of_classes:
  desc: null
  value: 10
no_of_features:
  desc: null
  value: 784
no_of_layers:
  desc: null
  value: 3
no_of_neurons:
  desc: null
  value: 256
optimizer:
  desc: null
  value: RMSprop
weight_decay:
  desc: null
  value: 0
