wandb_version: 1

_artifact_callback:
  desc: null
  value: wandb.sdk.wandb_run.Run._config_artifact_callback
_callback:
  desc: null
  value: wandb.sdk.wandb_run.Run._config_callback
_items:
  desc: null
  value:
    __doc__: "Config object.\n\n    Config objects are intended to hold all of the\
      \ hyperparameters associated with\n    a wandb run and are saved with the run\
      \ object when `wandb.init` is called.\n\n    We recommend setting `wandb.config`\
      \ once at the top of your training experiment or\n    setting the config as\
      \ a parameter to init, ie. `wandb.init(config=my_config_dict)`\n\n    You can\
      \ create a file called `config-defaults.yaml`, and it will automatically be\n\
      \    loaded into `wandb.config`. See https://docs.wandb.com/guides/track/config#file-based-configs.\n\
      \n    You can also load a config YAML file with your custom name and pass the\
      \ filename\n    into `wandb.init(config=\"special_config.yaml\")`.\n    See\
      \ https://docs.wandb.com/guides/track/config#file-based-configs.\n\n    Examples:\n\
      \        Basic usage\n        ```\n        wandb.config.epochs = 4\n       \
      \ wandb.init()\n        for x in range(wandb.config.epochs):\n            #\
      \ train\n        ```\n\n        Using wandb.init to set config\n        ```\n\
      \        wandb.init(config={\"epochs\": 4, \"batch_size\": 32})\n        for\
      \ x in range(wandb.config.epochs):\n            # train\n        ```\n\n   \
      \     Nested configs\n        ```\n        wandb.config['train']['epochs'] =\
      \ 4\n        wandb.init()\n        for x in range(wandb.config['train']['epochs']):\n\
      \            # train\n        ```\n\n        Using absl flags\n        ```\n\
      \        flags.DEFINE_string(‘model’, None, ‘model to run’) # name, default,\
      \ help\n        wandb.config.update(flags.FLAGS) # adds all absl flags to config\n\
      \        ```\n\n        Argparse flags\n        ```python\n        wandb.init()\n\
      \        wandb.config.epochs = 4\n\n        parser = argparse.ArgumentParser()\n\
      \        parser.add_argument(\n            \"-b\",\n            \"--batch-size\"\
      ,\n            type=int,\n            default=8,\n            metavar=\"N\"\
      ,\n            help=\"input batch size for training (default: 8)\",\n      \
      \  )\n        args = parser.parse_args()\n        wandb.config.update(args)\n\
      \        ```\n\n        Using TensorFlow flags (deprecated in tensorflow v2)\n\
      \        ```python\n        flags = tf.app.flags\n        flags.DEFINE_string(\"\
      data_dir\", \"/tmp/data\")\n        flags.DEFINE_integer(\"batch_size\", 128,\
      \ \"Batch size.\")\n        wandb.config.update(flags.FLAGS)  # adds all of\
      \ the tensorflow flags to config\n        ```\n    "
    _name: wandb.config
    _wandb: {}
    activation: relu
    batchsize: 128
    eta: 0.0001
    initialization: he
    loss: cross
    max_epochs: 10
    no_of_classes: 10
    no_of_features: 784
    no_of_layers: 3
    no_of_neurons: 512
    optimizer: adam
    weight_decay: 0.0005
_locked:
  desc: null
  value:
    activation: 0
    batchsize: 0
    eta: 0
    initialization: 0
    loss: 0
    max_epochs: 0
    no_of_classes: 0
    no_of_features: 0
    no_of_layers: 0
    no_of_neurons: 0
    optimizer: 0
    weight_decay: 0
_settings:
  desc: null
  value: '<Settings {''_args'': None, ''_cli_only_mode'': None, ''_colab'': False,
    ''_config_dict'': None, ''_console'': <SettingsConsole.WRAP: 1>, ''_cuda'': None,
    ''_disable_meta'': None, ''_disable_service'': False, ''_disable_stats'': None,
    ''_disable_viewer'': None, ''_except_exit'': None, ''_executable'': ''/opt/homebrew/opt/python@3.10/bin/python3.10'',
    ''_flow_control_custom'': False, ''_flow_control_disabled'': False, ''_internal_check_process'':
    8, ''_internal_queue_timeout'': 2, ''_jupyter'': True, ''_jupyter_name'': ''73589f2a-fac6-4874-90b2-332b47a32ea6'',
    ''_jupyter_path'': ''Assignment_1-jvsc-b0e6f116-d7c4-4be0-a282-f5acc873b644833d40e0-89ee-4a58-93f8-9c6e0e8f96b0.ipynb'',
    ''_jupyter_root'': ''/Users/crysiswar999/Documents/GitHub/CS6910-Assignment-1'',
    ''_kaggle'': False, ''_live_policy_rate_limit'': None, ''_live_policy_wait_time'':
    None, ''_log_level'': None, ''_network_buffer'': None, ''_noop'': False, ''_offline'':
    False, ''_sync'': False, ''_os'': ''macOS-12.6-arm64-arm-64bit'', ''_platform'':
    ''darwin'', ''_python'': ''3.10.6'', ''_runqueue_item_id'': None, ''_save_requirements'':
    True, ''_service_transport'': None, ''_service_wait'': 30.0, ''_start_datetime'':
    datetime.datetime(2023, 3, 9, 22, 41, 37, 667994), ''_start_time'': 1678381897.667994,
    ''_stats_pid'': 37860, ''_stats_sample_rate_seconds'': 2.0, ''_stats_samples_to_average'':
    15, ''_stats_join_assets'': True, ''_stats_neuron_monitor_config_path'': None,
    ''_stats_open_metrics_endpoints'': None, ''_stats_open_metrics_filters'': {''.*'':
    {}}, ''_tmp_code_dir'': ''/Users/crysiswar999/Documents/GitHub/CS6910-Assignment-1/wandb/run-20230309_224137-vyj2r77q/tmp/code'',
    ''_tracelog'': None, ''_unsaved_keys'': None, ''_windows'': False, ''allow_val_change'':
    None, ''anonymous'': None, ''api_key'': ''***REDACTED***'', ''base_url'': ''https://api.wandb.ai'',
    ''code_dir'': None, ''config_paths'': None, ''console'': ''auto'', ''deployment'':
    ''cloud'', ''disable_code'': None, ''disable_git'': False, ''disable_hints'':
    None, ''disable_job_creation'': False, ''disabled'': False, ''docker'': None,
    ''email'': ''cs22m031@smail.iitm.ac.in'', ''entity'': ''cs22m031'', ''files_dir'':
    ''/Users/crysiswar999/Documents/GitHub/CS6910-Assignment-1/wandb/run-20230309_224137-vyj2r77q/files'',
    ''force'': None, ''git_commit'': ''2f4ba94ae7966c377af4ae945bdaf0c224b93a3d'',
    ''git_remote'': ''origin'', ''git_remote_url'': ''https://github.com/Bibhuti-Majhi/CS6910-Assignment-1.git'',
    ''git_root'': None, ''heartbeat_seconds'': 30, ''host'': ''Bibhutis-Air.iitmlan'',
    ''ignore_globs'': (), ''init_timeout'': 60.0, ''is_local'': False, ''label_disable'':
    None, ''launch'': None, ''launch_config_path'': None, ''log_dir'': ''/Users/crysiswar999/Documents/GitHub/CS6910-Assignment-1/wandb/run-20230309_224137-vyj2r77q/logs'',
    ''log_internal'': ''/Users/crysiswar999/Documents/GitHub/CS6910-Assignment-1/wandb/run-20230309_224137-vyj2r77q/logs/debug-internal.log'',
    ''log_symlink_internal'': ''/Users/crysiswar999/Documents/GitHub/CS6910-Assignment-1/wandb/debug-internal.log'',
    ''log_symlink_user'': ''/Users/crysiswar999/Documents/GitHub/CS6910-Assignment-1/wandb/debug.log'',
    ''log_user'': ''/Users/crysiswar999/Documents/GitHub/CS6910-Assignment-1/wandb/run-20230309_224137-vyj2r77q/logs/debug.log'',
    ''login_timeout'': None, ''magic'': None, ''mode'': ''online'', ''notebook_name'':
    None, ''problem'': ''fatal'', ''program'': ''<python with no main file>'', ''program_relpath'':
    None, ''project'': ''CS6910_DL_assignment_1'', ''project_url'': ''https://wandb.ai/cs22m031/CS6910_DL_assignment_1'',
    ''quiet'': None, ''reinit'': None, ''relogin'': None, ''resume'': None, ''resume_fname'':
    ''/Users/crysiswar999/Documents/GitHub/CS6910-Assignment-1/wandb/wandb-resume.json'',
    ''resumed'': False, ''root_dir'': ''/Users/crysiswar999/Documents/GitHub/CS6910-Assignment-1'',
    ''run_group'': None, ''run_id'': ''vyj2r77q'', ''run_job_type'': None, ''run_mode'':
    ''run'', ''run_name'': ''wobbly-sweep-1'', ''run_notes'': None, ''run_tags'':
    None, ''run_url'': ''https://wandb.ai/cs22m031/CS6910_DL_assignment_1/runs/vyj2r77q'',
    ''sagemaker_disable'': None, ''save_code'': None, ''settings_system'': ''/Users/crysiswar999/.config/wandb/settings'',
    ''settings_workspace'': ''/Users/crysiswar999/Documents/GitHub/CS6910-Assignment-1/wandb/settings'',
    ''show_colors'': None, ''show_emoji'': None, ''show_errors'': True, ''show_info'':
    True, ''show_warnings'': True, ''silent'': False, ''start_method'': None, ''strict'':
    None, ''summary_errors'': None, ''summary_timeout'': 60, ''summary_warnings'':
    5, ''sweep_id'': ''ykswcbhg'', ''sweep_param_path'': ''/Users/crysiswar999/Documents/GitHub/CS6910-Assignment-1/wandb/sweep-ykswcbhg/config-vyj2r77q.yaml'',
    ''sweep_url'': ''https://wandb.ai/cs22m031/CS6910_DL_assignment_1/sweeps/ykswcbhg'',
    ''symlink'': True, ''sync_dir'': ''/Users/crysiswar999/Documents/GitHub/CS6910-Assignment-1/wandb/run-20230309_224137-vyj2r77q'',
    ''sync_file'': ''/Users/crysiswar999/Documents/GitHub/CS6910-Assignment-1/wandb/run-20230309_224137-vyj2r77q/run-vyj2r77q.wandb'',
    ''sync_symlink_latest'': ''/Users/crysiswar999/Documents/GitHub/CS6910-Assignment-1/wandb/latest-run'',
    ''system_sample'': 15, ''system_sample_seconds'': 2, ''table_raise_on_max_row_limit_exceeded'':
    False, ''timespec'': ''20230309_224137'', ''tmp_dir'': ''/Users/crysiswar999/Documents/GitHub/CS6910-Assignment-1/wandb/run-20230309_224137-vyj2r77q/tmp'',
    ''username'': ''crysiswar999'', ''wandb_dir'': ''/Users/crysiswar999/Documents/GitHub/CS6910-Assignment-1/wandb/''}>'
_users:
  desc: null
  value:
    sweep: 0
_users_cnt:
  desc: null
  value: 1
_users_inv:
  desc: null
  value:
    '0': sweep
_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.6
    start_time: 1678382653.474122
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      - 37
      4: 3.10.6
      5: 0.13.11
      8:
      - 1
      - 4
      - 5
activation:
  desc: null
  value: relu
batchsize:
  desc: null
  value: 64
eta:
  desc: null
  value: 0.0001
initialization:
  desc: null
  value: he
loss:
  desc: null
  value: cross
max_epochs:
  desc: null
  value: 5
no_of_classes:
  desc: null
  value: 10
no_of_features:
  desc: null
  value: 784
no_of_layers:
  desc: null
  value: 5
no_of_neurons:
  desc: null
  value: 256
optimizer:
  desc: null
  value: adam
weight_decay:
  desc: null
  value: 0.0005
