wandb_version: 1

activation:
  value: sigmoid
batchsize:
  value: 64
eta:
  value: 0.1
initialization:
  value: uniform
loss:
  value: cross
max_epochs:
  value: 5
no_of_classes:
  value: 10
no_of_features:
  value: 784
no_of_layers:
  value: 4
no_of_neurons:
  value: 128
optimizer:
  value: nadam
weight_decay:
  value: 0.001
