wandb_version: 1

activation:
  value: sigmoid
batchsize:
  value: 128
eta:
  value: 0.0001
initialization:
  value: xavier
loss:
  value: cross
max_epochs:
  value: 10
no_of_classes:
  value: 10
no_of_features:
  value: 784
no_of_layers:
  value: 3
no_of_neurons:
  value: 32
optimizer:
  value: RMSprop
weight_decay:
  value: 0.001
