wandb_version: 1

activation:
  value: tanh
batchsize:
  value: 64
eta:
  value: 0.0001
initialization:
  value: he
loss:
  value: cross
max_epochs:
  value: 10
no_of_classes:
  value: 10
no_of_features:
  value: 784
no_of_layers:
  value: 5
no_of_neurons:
  value: 64
optimizer:
  value: nadam
weight_decay:
  value: 0
