wandb_version: 1

activation:
  value: relu
batchsize:
  value: 128
eta:
  value: 0.0001
initialization:
  value: uniform
loss:
  value: cross
max_epochs:
  value: 10
no_of_classes:
  value: 10
no_of_features:
  value: 784
no_of_layers:
  value: 6
no_of_neurons:
  value: 32
optimizer:
  value: RMSprop
weight_decay:
  value: 0.0005
