wandb_version: 1

activation:
  value: relu
batchsize:
  value: 128
eta:
  value: 0.001
initialization:
  value: xavier
loss:
  value: cross
max_epochs:
  value: 5
no_of_classes:
  value: 10
no_of_features:
  value: 784
no_of_layers:
  value: 4
no_of_neurons:
  value: 32
optimizer:
  value: mgd
weight_decay:
  value: 0.001
