wandb_version: 1

activation:
  value: tanh
batchsize:
  value: 32
eta:
  value: 0.001
initialization:
  value: xavier
loss:
  value: cross
max_epochs:
  value: 10
no_of_classes:
  value: 10
no_of_features:
  value: 784
no_of_layers:
  value: 3
no_of_neurons:
  value: 64
optimizer:
  value: nesterov
weight_decay:
  value: 0.001
