wandb_version: 1

activation:
  value: relu
batchsize:
  value: 16
eta:
  value: 0.1
initialization:
  value: he
loss:
  value: MSE
max_epochs:
  value: 5
no_of_classes:
  value: 10
no_of_features:
  value: 784
no_of_layers:
  value: 6
no_of_neurons:
  value: 64
optimizer:
  value: nesterov
weight_decay:
  value: 0.0005
