wandb_version: 1

activation:
  value: sigmoid
batchsize:
  value: 128
eta:
  value: 0.1
initialization:
  value: normal
loss:
  value: mse
max_epochs:
  value: 5
no_of_classes:
  value: 10
no_of_features:
  value: 784
no_of_layers:
  value: 3
no_of_neurons:
  value: 128
optimizer:
  value: nesterov
weight_decay:
  value: 0
